/* eslint-disable */
// @ts-nocheck

/**
 * The content of the file generated by the script content, if necessary, please refer to the use of custom templates:我是自定义模板使用文档地址
 *
 */
declare namespace CUSTOM_PLUGIN {
     interface IOrder {
          /**没有提供描述 */
      id?: number;
          /**没有提供描述 */
      petId?: number;
          /**没有提供描述 */
      quantity?: number;
          /**没有提供描述 */
      shipDate?: string;
          /**Order Status */
      status?: string;
          /**没有提供描述 */
      complete?: boolean;
    }
     interface ICategory {
          /**没有提供描述 */
      id?: number;
          /**没有提供描述 */
      name?: string;
    }
     interface IUser {
          /**没有提供描述 */
      id?: number;
          /**没有提供描述 */
      username?: string;
          /**没有提供描述 */
      firstName?: string;
          /**没有提供描述 */
      lastName?: string;
          /**没有提供描述 */
      email?: string;
          /**没有提供描述 */
      password?: string;
          /**没有提供描述 */
      phone?: string;
          /**User Status */
      userStatus?: number;
    }
     interface ITag {
          /**没有提供描述 */
      id?: number;
          /**没有提供描述 */
      name?: string;
    }
     interface IPet {
          /**没有提供描述 */
      id?: number;
          /**没有提供描述 */
      category?: ICategory;
          /**没有提供描述 */
      name?: string;
          /**没有提供描述 */
      photoUrls?: string[];
          /**没有提供描述 */
      tags?: ITag[];
          /**pet status in the store */
      status?: string;
    }
     interface IApiResponse {
          /**没有提供描述 */
      code?: number;
          /**没有提供描述 */
      type?: string;
          /**没有提供描述 */
      message?: string;
    }
     interface IPetfindByStatusQueryParams {
          /**Status values that need to be considered for filter */
      status?: string[];
    }
     interface IPetfindByTagsQueryParams {
          /**Tags to filter by */
      tags?: string[];
    }
     interface IUserloginQueryParams {
          /**The user name for login */
      username?: string;
          /**The password for login in clear text */
      password?: string;
    }
  }

global.CUSTOM_PLUGIN = CUSTOM_PLUGIN;
